import { runQuery } from '~/server/database/db'
import { requireAuth, requirePermission } from '~/server/utils/auth'

export default defineEventHandler(async (event) => {
  // Require authentication and super_admin permission
  requireAuth(event)
  requirePermission('manage_content')(event) // Super admin only

  try {
    console.log('[Database Backup] Starting backup process...')

    // Get all tables
    const tables = await runQuery('SHOW TABLES')
    const tableNames = tables.map((row: any) => Object.values(row)[0] as string)

    console.log(`[Database Backup] Found ${tableNames.length} tables`)

    // Build SQL dump
    let sqlDump = `-- MySQL Database Backup
-- Database: ${process.env.MYSQL_DATABASE}
-- Date: ${new Date().toISOString()}
-- Generated by: StPaulus Admin Panel
--
-- =====================================================

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

`

    // Backup each table
    for (const tableName of tableNames) {
      console.log(`[Database Backup] Processing table: ${tableName}`)

      // Get CREATE TABLE statement
      const createResult = await runQuery(`SHOW CREATE TABLE \`${tableName}\``)
      const createStatement = (createResult[0] as any)['Create Table']

      sqlDump += `\n-- =====================================================\n`
      sqlDump += `-- Table structure for: ${tableName}\n`
      sqlDump += `-- =====================================================\n\n`
      sqlDump += `DROP TABLE IF EXISTS \`${tableName}\`;\n`
      sqlDump += createStatement + ';\n\n'

      // Get table data
      const rows = await runQuery(`SELECT * FROM \`${tableName}\``)

      if (rows.length > 0) {
        sqlDump += `-- =====================================================\n`
        sqlDump += `-- Data for table: ${tableName}\n`
        sqlDump += `-- =====================================================\n\n`
        sqlDump += `INSERT INTO \`${tableName}\` VALUES\n`

        const values = rows.map((row: any) => {
          const escapedValues = Object.values(row).map(val => {
            if (val === null) return 'NULL'
            if (typeof val === 'number') return val
            if (val instanceof Date) return `'${(val as Date).toISOString().slice(0, 19).replace('T', ' ')}'`
            // Escape single quotes and backslashes
            const escaped = String(val).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
            return `'${escaped}'`
          })
          return `(${escapedValues.join(', ')})`
        })

        sqlDump += values.join(',\n') + ';\n\n'
      }
    }

    sqlDump += `\nSET FOREIGN_KEY_CHECKS=1;\n`

    console.log('[Database Backup] Backup completed successfully')

    // Return as downloadable file
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
    const filename = `stpaulus_backup_${timestamp}.sql`

    setResponseHeaders(event, {
      'Content-Type': 'application/sql',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': Buffer.byteLength(sqlDump, 'utf8').toString()
    })

    return sqlDump

  } catch (error: any) {
    console.error('[Database Backup] Error:', error)
    throw createError({
      statusCode: 500,
      statusMessage: 'Failed to create database backup',
      message: error.message
    })
  }
})
