[phases.setup]
nixPkgs = ["nodejs_22"]
aptPkgs = []

[phases.install]
cmds = ["PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install --ignore-scripts --force --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"
