-- Sample Kronik Data for St. Paulus Juanda Parish
-- 5 entries per category (Gereja, DPP, BGKP, Wilayah, Lingkungan)

-- KATEGORI GEREJA (5 entries)
INSERT INTO kronik_entries (
  category_id, section_id, what_title, what_description, when_date, when_duration, 
  where_location, where_address, who_involved, why_purpose, how_process, status
) VALUES
(1, NULL, 
  'Perayaan Ekaristi Paskah 2025', 
  'Perayaan Ekaristi Paskah dihadiri oleh seluruh umat Paroki St. Paulus dengan tema "Kristus Bangkit, Harapan Dunia". Misa dipimpin oleh Pastor Paroki dengan diiringi paduan suara dan orkestra.',
  '2025-04-20', '180 menit',
  'Gereja St. Paulus Juanda', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Dewan Pastoral, Tim Liturgi, Paduan Suara, Umat Paroki',
  'Merayakan kebangkitan Yesus Kristus dan memperkuat iman umat dalam menghadapi tantangan hidup',
  'Prosesi dimulai dengan perarakan lilin Paskah, pembacaan Kitab Suci, homili, dan diakhiri dengan berkat dan perutusan. Acara dilanjutkan dengan salam-salaman dan fellowship di halaman gereja.',
  'published'),

(1, NULL,
  'Misa Syukur HUT Paroki ke-50',
  'Misa Syukur memperingati 50 tahun berdirinya Paroki St. Paulus Juanda yang dihadiri oleh Uskup Keuskupan Surabaya, para imam se-Keuskupan, dan ribuan umat.',
  '2025-03-15', '240 menit',
  'Gereja St. Paulus Juanda', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Uskup Surabaya, Pastor Paroki, Para Imam, Dewan Pastoral, Seluruh Umat Paroki',
  'Mengucap syukur atas perjalanan 50 tahun Paroki St. Paulus dan memperkuat komitmen dalam pelayanan',
  'Misa Kudus dilangsungkan secara khidmat dengan tata cara liturgi agung. Setelah misa, diadakan acara syukuran dengan pemotongan tumpeng dan pentas seni dari berbagai kategori usia.',
  'published'),

(1, NULL,
  'Adorasi dan Doa Rosario Harian',
  'Kegiatan adorasi Sakramen Mahakudus dan doa rosario yang diadakan setiap hari Selasa dan Jumat sebagai bentuk devosi umat kepada Yesus dalam Ekaristi.',
  '2025-02-25', '60 menit',
  'Kapel Adorasi St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Tim Adorasi, Umat Paroki',
  'Memperdalam spiritualitas umat melalui doa dan adorasi Sakramen Mahakudus',
  'Adorasi dimulai dengan nyanyian pembuka, diikuti dengan saat hening, pembacaan Kitab Suci, refleksi, doa rosario, dan berkat sakramen. Umat bergantian memimpin doa rosario setiap minggu.',
  'published'),

(1, NULL,
  'Pelatihan Lektor dan Prodiakon',
  'Pelatihan berkala untuk para lektor dan prodiakon guna meningkatkan kualitas pelayanan liturgi di Gereja St. Paulus Juanda.',
  '2025-01-20', '180 menit',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Tim Liturgi, Para Lektor, Para Prodiakon',
  'Meningkatkan kemampuan dan pemahaman para lektor dalam mewartakan Sabda Allah serta para prodiakon dalam melayani liturgi',
  'Pelatihan meliputi teknik membaca Kitab Suci, pemahaman liturgi, praktek langsung, dan evaluasi. Materi disampaikan oleh Pastor Paroki dan Tim Liturgi yang berpengalaman.',
  'published'),

(1, NULL,
  'Misa Malam Natal 2024',
  'Perayaan Misa Malam Natal dengan tema "Terang Kristus Menerangi Dunia". Misa dihadiri oleh ribuan umat dengan tata cara liturgi yang khidmat.',
  '2024-12-24', '120 menit',
  'Gereja St. Paulus Juanda', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Tim Liturgi, Paduan Suara, Umat Paroki',
  'Merayakan kelahiran Yesus Kristus sebagai Juru Selamat dunia',
  'Misa dimulai dengan prosesi dan penempatan patung Bayi Yesus di palungan, diikuti dengan pembacaan Injil Natal, homili, dan perarakan persembahan. Misa diakhiri dengan nyanyian "Malam Kudus" dan berkat Natal.',
  'published');

-- KATEGORI DPP (Dewan Pastoral Paroki) - 5 entries
INSERT INTO kronik_entries (
  category_id, section_id, what_title, what_description, when_date, when_duration, 
  where_location, where_address, who_involved, why_purpose, how_process, status
) VALUES
(2, 1,
  'Rapat Koordinasi DPP Triwulan I 2025',
  'Rapat koordinasi Dewan Pastoral Paroki membahas program kerja triwulan pertama tahun 2025 dan evaluasi program tahun sebelumnya.',
  '2025-01-15', '180 menit',
  'Ruang Rapat Pastoran', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Ketua DPP, Pengurus DPP, Koordinator Seksi',
  'Menyusun dan mengevaluasi program kerja pastoral paroki untuk meningkatkan pelayanan kepada umat',
  'Rapat dibuka dengan doa, dilanjutkan presentasi evaluasi program 2024, diskusi program 2025, pembagian tugas, dan diakhiri dengan doa penutup serta makan bersama.',
  'published'),

(2, 2,
  'Pelatihan Pemberdayaan Ekonomi Umat',
  'Program pelatihan wirausaha dan pemberdayaan ekonomi umat yang dikoordinasikan oleh Seksi Sosial Ekonomi DPP.',
  '2025-02-10', '240 menit',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Seksi Sosial Ekonomi DPP, Narasumber Wirausaha, Umat Paroki',
  'Memberdayakan umat dalam aspek ekonomi melalui pelatihan kewirausahaan dan keterampilan',
  'Pelatihan meliputi materi motivasi wirausaha, manajemen usaha kecil, pemasaran digital, dan praktek pembuatan produk. Peserta mendapat sertifikat dan bantuan modal usaha.',
  'published'),

(2, 3,
  'Retret DPP dan Tim Inti Paroki',
  'Retret tahunan bagi pengurus DPP dan tim inti pelayanan paroki untuk pembaruan spiritual dan evaluasi pelayanan.',
  '2025-03-08', '1 hari',
  'Wisma Retret Canossa', 'Tretes, Pasuruan',
  'Pastor Paroki, Pengurus DPP, Tim Inti Pelayanan Paroki',
  'Memperbaharui semangat pelayanan dan memperkuat komitmen dalam menjalankan tugas pastoral',
  'Retret dipandu oleh pembimbing rohani dengan tema "Melayani dengan Hati Kristus". Kegiatan meliputi renungan, sharing, misa kudus, dan rekonsiliasi.',
  'published'),

(2, 4,
  'Pertemuan Evaluasi Program Katekese',
  'Pertemuan koordinasi untuk mengevaluasi dan meningkatkan program katekese bagi anak, remaja, dan calon baptis dewasa.',
  '2025-01-25', '150 menit',
  'Ruang Rapat Pastoran', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Seksi Kateketik DPP, Para Katekis, Pastor Paroki',
  'Meningkatkan kualitas pengajaran iman Katolik bagi semua kelompok usia di paroki',
  'Evaluasi mencakup metode pengajaran, materi katekese, jadwal pertemuan, dan kebutuhan sarana prasarana. Dihasilkan rekomendasi perbaikan program katekese.',
  'published'),

(2, 5,
  'Peluncuran Website Paroki yang Diperbarui',
  'Peluncuran resmi website paroki yang telah diperbarui dengan fitur-fitur baru termasuk sistem kronik digital dan manajemen konten.',
  '2025-02-01', '120 menit',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Seksi Komunikasi DPP, Tim IT, Pastor Paroki, Pengurus DPP',
  'Meningkatkan komunikasi dan informasi kepada umat melalui media digital yang lebih modern dan user-friendly',
  'Acara dimulai dengan presentasi fitur-fitur baru website, demo penggunaan, sosialisasi kepada pengurus seksi, dan launching resmi oleh Pastor Paroki.',
  'published');

-- KATEGORI BGKP (Bina Iman Anak, Remaja, Muda) - 5 entries
INSERT INTO kronik_entries (
  category_id, section_id, what_title, what_description, when_date, when_duration, 
  where_location, where_address, who_involved, why_purpose, how_process, status
) VALUES
(3, 6,
  'Perkemahan Anak Katolik (PAK) 2025',
  'Kegiatan perkemahan untuk anak-anak Katolik se-paroki dengan tema "Yesus Sahabatku" yang diikuti oleh 150 anak.',
  '2025-02-15', '3 hari 2 malam',
  'Bumi Perkemahan Trawas', 'Trawas, Mojokerto',
  'Tim Bina Iman Anak, Pendamping, Anak-anak Katolik Paroki',
  'Membentuk karakter anak Katolik melalui kegiatan outdoor, pembinaan iman, dan kerjasama tim',
  'Kegiatan meliputi upacara pembukaan, api unggun, games, katekese, misa kudus, outbound, pentas seni, dan malam keakraban. Anak-anak menginap di tenda dan belajar kemandirian.',
  'published'),

(3, 7,
  'Retreat Remaja "Youth Arise"',
  'Retret khusus remaja dengan pembicara dari komunitas katolik Jakarta, membahas identitas diri sebagai remaja Katolik di era digital.',
  '2025-03-01', '1 hari',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Tim Bina Iman Remaja, Pembicara Tamu, Remaja Katolik Paroki',
  'Membantu remaja menemukan jati diri dan menguatkan iman di tengah tantangan zaman',
  'Retret dimulai dengan ice breaking, sesi sharing, materi motivasi, adorasi, dan misa kudus. Remaja diajak untuk berani berkomitmen hidup mengikuti  Kristus.',
  'published'),

(3, 8,
  'Bakti Sosial Pemuda Katolik',
  'Kegiatan bakti sosial pemuda katolik mengunjungi panti asuhan dan membagikan sembako serta mengadakan hiburan untuk anak panti.',
  '2025-01-28', '4 jam',
  'Panti Asuhan Yatim Piatu Sidoarjo', 'Jl. Lingkar Barat, Sidoarjo',
  'Orang Muda Katolik (OMK) Paroki St. Paulus, Anak-anak Panti Asuhan',
  'Menumbuhkan kepekaan sosial dan semangat berbagi kasih kepada sesama yang membutuhkan',
  'Pemuda membawa bantuan sembako dan keperluan anak panti, mengadakan games, bernyanyi bersama, dan berinteraksi dengan anak-anak panti. Acara diakhiri dengan doa bersama.',
  'published'),

(3, 6,
  'Katekese Komuni Pertama Angkatan 2025',
  'Program katekese persiapan penerimaan Komuni Pertama bagi 80 anak kelas 3-4 SD se-paroki.',
  '2025-01-10', '12 pertemuan',
  'Ruang Bina Iman Gereja', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Tim Katekis, Pastor Paroki, Anak-anak calon komunikan, Orang tua',
  'Mempersiapkan anak-anak untuk menerima Sakramen Ekaristi Pertama kali dengan penuh kesadaran',
  'Katekese dilaksanakan setiap hari Minggu setelah misa anak. Materi meliputi pengenalan Ekaristi, doa dasar, kisah Yesus, dan praktek perayaan. Orang tua dilibatkan dalam pendampingan di rumah.',
  'published'),

(3, 8,
  'Live-in OMK di Desa Terpencil',
  'Program live-in Orang Muda Katolik selama 3 hari di desa terpencil untuk belajar hidup sederhana dan melayani masyarakat.',
  '2025-02-22', '3 hari 2 malam',
  'Desa Sendang Kulon', 'Lamongan, Jawa Timur',
  'Orang Muda Katolik (OMK), Pendamping, Masyarakat Desa',
  'Melatih kepekaan sosial, kesederhanaan hidup, dan semangat melayani di tengah masyarakat',
  'Pemuda tinggal bersama keluarga desa, membantu kegiatan pertanian, mengajar anak-anak, mengadakan permainan, dan kerja bakti. Pengalaman ini dibagikan dalam sesi sharing dan evaluasi.',
  'published');

-- KATEGORI WILAYAH - 5 entries
INSERT INTO kronik_entries (
  category_id, section_id, what_title, what_description, when_date, when_duration, 
  where_location, where_address, who_involved, why_purpose, how_process, status
) VALUES
(4, NULL,
  'Perayaan Ekaristi Wilayah St. Petrus',
  'Misa bulanan Wilayah St. Petrus yang dipimpin oleh Pastor Paroki dan dihadiri oleh umat dari 5 lingkungan.',
  '2025-02-05', '90 menit',
  'Rumah Ketua Wilayah St. Petrus', 'Perumahan Taman Pinang Indah Blok A',
  'Pastor Paroki, Koordinator Wilayah, Ketua Lingkungan, Umat Wilayah St. Petrus',
  'Mempererat persaudaraan antar lingkungan dalam satu wilayah melalui perayaan iman bersama',
  'Misa dilaksanakan di rumah ketua wilayah dengan suasana kekeluargaan. Setelah misa, diadakan sharing dan fellowship makan bersama. Umat berbagi kabar sukacita dan kesulitan.',
  'published'),

(4, NULL,
  'Lomba Paduan Suara Antar Wilayah',
  'Lomba paduan suara tingkat wilayah dalam rangka memeriahkan HUT Paroki, diikuti oleh 8 wilayah se-paroki.',
  '2025-03-10', '4 jam',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Tim Juri, Koordinator Wilayah, Anggota Paduan Suara Wilayah',
  'Mengembangkan bakat seni musik liturgi dan mempererat kebersamaan antar wilayah',
  'Setiap wilayah menampilkan 2 lagu wajib liturgi dan 1 lagu pilihan. Penilaian meliputi harmonisasi, ketepatan nada, kompaksi, dan penampilan. Pemenang mendapat piala bergilir dan hadiah.',
  'published'),

(4, NULL,
  'Rapat Koordinasi Ketua Wilayah Se-Paroki',
  'Pertemuan rutin para ketua wilayah dengan Pastor Paroki dan DPP untuk koordinasi program pastoral.',
  '2025-01-18', '120 menit',
  'Ruang Rapat Pastoran', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Ketua DPP, Para Koordinator Wilayah',
  'Menyelaraskan program pastoral paroki dengan kegiatan di tingkat wilayah dan lingkungan',
  'Rapat membahas evaluasi program triwulan sebelumnya, rencana kegiatan triwulan mendatang, permasalahan di wilayah, dan solusi bersama. Setiap koordinator wilayah menyampaikan laporan.',
  'published'),

(4, NULL,
  'Ziarah Wilayah ke Gua Maria Sendang Sono',
  'Kegiatan ziarah bersama Wilayah St. Maria ke Gua Maria Sendang Sono sebagai bentuk devosi kepada Bunda Maria.',
  '2025-02-18', '1 hari',
  'Gua Maria Sendang Sono', 'Kalibawang, Kulon Progo, Yogyakarta',
  'Koordinator Wilayah St. Maria, Umat Wilayah St. Maria',
  'Memperdalam devosi kepada Bunda Maria dan mempererat persaudaraan umat dalam satu wilayah',
  'Perjalanan ditempuh dengan bus pariwisata. Kegiatan di lokasi meliputi jalan salib, doa rosario, misa kudus di gua, dan doa pribadi. Perjalanan pulang diselingi dengan bernyanyi bersama.',
  'published'),

(4, NULL,
  'Bakti Sosial Wilayah untuk Korban Banjir',
  'Kegiatan penggalangan dana dan distribusi bantuan untuk korban banjir di wilayah Sidoarjo yang dikoordinir oleh Wilayah St. Yosef.',
  '2025-01-30', '3 hari',
  'Desa Tulangan yang Terdampak Banjir', 'Tulangan, Sidoarjo',
  'Koordinator Wilayah St. Yosef, Relawan Umat, Masyarakat Korban Banjir',
  'Mewujudkan kasih Kristus melalui kepedulian kepada saudara yang tertimpa musibah',
  'Wilayah menggalang donasi dari umat, membeli kebutuhan pokok, dan mendistribusikan langsung ke pengungsian. Tim relawan juga membantu membersihkan rumah warga yang terendam.',
  'published');

-- KATEGORI LINGKUNGAN - 5 entries
INSERT INTO kronik_entries (
  category_id, section_id, what_title, what_description, when_date, when_duration, 
  where_location, where_address, who_involved, why_purpose, how_process, status
) VALUES
(5, NULL,
  'Misa Lingkungan Keluarga Kudus',
  'Perayaan Ekaristi bulanan Lingkungan Keluarga Kudus yang dipimpin oleh Pastor Pembantu dengan sharing kitab suci.',
  '2025-02-12', '120 menit',
  'Rumah Bapak Antonius Setiawan', 'Jl. Raya Bandung No. 45',
  'Pastor Pembantu, Ketua Lingkungan, Anggota Lingkungan Keluarga Kudus',
  'Memperkuat iman umat melalui perayaan Ekaristi dan sharing Sabda Tuhan dalam keluarga kecil',
  'Misa diawali dengan salam dan pengantar oleh ketua lingkungan, dilanjutkan perayaan ekaristi, sharing kitab suci, doa spontan, dan diakhiri dengan makan bersama. Suasana sangat kekeluargaan.',
  'published'),

(5, NULL,
  'Arisan dan Doa Lingkungan St. Monica',
  'Pertemuan rutin bulanan Lingkungan St. Monica dengan acara doa rosario, arisan, dan sharing kehidupan beriman.',
  '2025-02-20', '90 menit',
  'Rumah Ibu Maria Susanti', 'Jl. Melati No. 12',
  'Ketua Lingkungan St. Monica, Anggota Lingkungan',
  'Mempererat persaudaraan dan saling mendukung dalam kehidupan beriman sehari-hari',
  'Pertemuan dimulai dengan doa rosario bersama, dilanjutkan arisan bulanan, sharing pengalaman iman, dan makan bersama. Anggota saling berbagi sukacita dan dukacita.',
  'published'),

(5, NULL,
  'Kunjungan Orang Sakit Lingkungan St. Mikael',
  'Kegiatan kunjungan dan pendampingan kepada anggota lingkungan yang sedang sakit oleh tim pastoral kesehatan lingkungan.',
  '2025-02-08', '3 jam',
  'Rumah-rumah anggota yang sakit', 'Berbagai lokasi di wilayah lingkungan',
  'Ketua Lingkungan St. Mikael, Tim Pastoral Kesehatan, Anggota Lingkungan',
  'Memberikan dukungan spiritual dan moral kepada saudara seiman yang sedang menderita sakit',
  'Tim mengunjungi 4 keluarga yang memiliki anggota sakit, mendoakan, mendengarkan keluh kesah, membawakan komuni suci, dan memberikan bantuan sesuai kebutuhan. Kunjungan dilakukan dengan penuh kasih.',
  'published'),

(5, NULL,
  'Gotong Royong Lingkungan St. Rafael',
  'Kegiatan kerja bakti membersihkan lingkungan sekitar dan renovasi ringan pos ronda yang digunakan untuk pertemuan lingkungan.',
  '2025-01-22', '4 jam',
  'Pos Ronda RT 05 RW 02', 'Jl. Anggrek Blok C',
  'Ketua Lingkungan St. Rafael, Anggota Lingkungan, Warga sekitar',
  'Membangun kebersamaan dan menjaga kebersihan lingkungan tempat tinggal warga',
  'Kegiatan dimulai pukul 07.00 dengan pembagian tugas: kelompok pembersihan halaman, pengecatan, dan perbaikan atap bocor. Setelah selesai, diadakan makan bersama yang dimasak oleh ibu-ibu lingkungan.',
  'published'),

(5, NULL,
  'Perayaan Ulang Tahun Lingkungan St. Gabriel',
  'Perayaan HUT ke-10 Lingkungan St. Gabriel dengan misa syukur dan acara kebersamaan seperti games dan pentas seni keluarga.',
  '2025-03-05', '180 menit',
  'Aula Gereja St. Paulus', 'Jl. Pahlawan No. 1, Sidoarjo',
  'Pastor Paroki, Ketua Lingkungan St. Gabriel, Seluruh Anggota Lingkungan',
  'Mengucap syukur atas 10 tahun perjalanan Lingkungan St. Gabriel dan mempererat kebersamaan antar anggota',
  'Acara dibuka dengan misa syukur, dilanjutkan ramah tamah, games keluarga, penampilan paduan suara lingkungan, slide show kenangan 10 tahun, pemotongan tumpeng, dan makan bersama.',
  'published');
